apiVersion: v1
kind: Service
metadata:
  name: subject4-data-show
  labels:
    app: subject-4
    component: data-show
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30490
  selector:
    app: subject-4
    component: data-show
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subject4-data-show
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subject-4
      component: data-show
  template:
    metadata:
      labels:
        app: subject-4
        component: data-show
    spec:
      containers:
      - name: mysql
        image: registry.cn-shanghai.aliyuncs.com/fusion-app/subject4-datashow-mysql:2.0.0
        ports:
        - containerPort: 3306 
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_DATABASE
          value: "hmt_project"
        - name: MYSQL_USERNAME
          value: "root"
        - name: MYSQL_PASSWORD
          value: "123456"
      - name: tomcat
        image: registry.cn-shanghai.aliyuncs.com/fusion-app/subject4-datashow-tomcat:2.0.0
        ports:
        - containerPort: 8080