apiVersion: v1
kind: Service
metadata:
  name: subject5-speaker
spec:
  type: NodePort
  selector:
    app: subject-5
    component: speaker
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30551
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subject5-speaker
  labels:
    app: subject-5
    component: speaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subject-5
      component: speaker
  template:
    metadata:
      labels:
        app: subject-5
        component: speaker
    spec:
      containers:
      - name: compute
        image: registry.cn-shanghai.aliyuncs.com/fusion-app/subject5-speaker:201911282009
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
        ports:
        - name: http
          containerPort: 5000
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30