apiVersion: fusionapp.io/v1alpha1
kind: Resource
metadata:
  name: coffee-maker-nju
  namespace: fusion-app-resources
spec:
  icon: "https://fusion-app-1253221273.cos.ap-shanghai.myqcloud.com/resource/coffeepot.png"
  aliasName: "东菱咖啡机（南大）"
  resourceKind: Edge
  accessMode: Exclusive
  phase: NotReady
  probeEnabled: false
  labels:
    io.fusionapp/kind: "smarthome"
    io.fusionapp/pos: "110"
    io.fusionapp.smarthome/vendor: "mi"
    io.fusionapp.smarthome/type: "coffeepot"
    io.fusionapp.smarthome/owner: "nju"
    io.fusionapp.smarthome/function: "make-coffee"
    io.fusionapp.smarthome/price: "4"
    "longitude": "116.328355" 
    "latitude": "39.993255"
    "x": "0.6744707550349607"
    "y": "0.5852621514438383"
  operation:
  - name: make-coffee
    price: 20
    httpAction:
      action: "GET"
      url: "http://39.106.6.6:8080/SCIDE/SCManager?action=executeContract&contractID=CoffeeNJU&operation=postMakeCoffee&arg=%22%22"
      headers:
        Accept: "*/*"
  - name: get-coffee-status
    price: 10
    httpAction:
      action: "GET"
      url: "http://39.106.6.6:8080/SCIDE/SCManager?action=executeContract&contractID=CoffeeNJU&operation=postGetEnvStatus&arg=%22%22"
      headers:
        Accept: "*/*"
  probeArgs:
    - --http-url
    - http://39.106.6.6:8080/SCIDE/SCManager?action=executeContract&contractID=CoffeeNJU&operation=postGetEnvStatus&arg=%22%22
    - --probe-interval
    - 8s
    - --http-headers
    - 'Accept: */*;'
    - --patch-creator
    - .data.data.State.value;/io.fusionapp.smarthome.coffeepot~1state;string
    - --patch-creator
    - .data.data.keepwarmtime.value;/io.fusionapp.smarthome.coffeepot~1keepwarmtime;string
