apiVersion: fusionapp.io/v1alpha1
kind: Resource
metadata:
  name: speaker-mi
  namespace: fusion-app-resources
spec:
  icon: "https://fusion-app-1253221273.cos.ap-shanghai.myqcloud.com/resource/speaker.png"
  aliasName: "小爱音箱"
  resourceKind: Edge
  accessMode: Exclusive
  phase: NotReady
  probeEnabled: false
  labels:
    io.fusionapp/kind: "smarthome"
    io.fusionapp/doi: "86.5000.470/YYDS813_SR159723"
    io.fusionapp/opRecord: "86.5000.470/YYDS813/RY123218,86.5000.470/YYDS813/RY123218"
    io.fusionapp/pos: "111"
    io.fusionapp.smarthome/vendor: "mi"
    io.fusionapp.smarthome/type: "speaker"
    io.fusionapp.smarthome/function: "speak"
    io.fusionapp.smarthome/price: "8"
    "longitude": "116.327639"
    "latitude": "39.993239"
    "x": "0.6403"
    "y": "0.6247"
    "3dx": "6.74"
    "3dy": "2.826"
    "3dz": "0.689"
  operation:
  - name: speak
    price: 5
    httpAction:
      action: "GET"
      url: "http://39.106.6.6:8080/SCIDE/SCManager?action=executeContract&contractID=XiaoMiAudio&operation=getAudioInfo&arg=%22%22"
      qeuery:
        arg: ""
      headers:
        Accept: "*/*"
  - name: get-order
    httpAction:
      action: "GET"
      url: "https://xiaomi.xuwang.tech/res"

