apiVersion: fusionapp.io/v1alpha1
kind: Resource
metadata:
  name: human-001
  namespace: fusion-app-resources
spec:
  aliasName: "众包员工"
  resourceKind: Human
  accessMode: Exclusive
  probeEnabled: false
  labels:
    io.fusionapp/kind: "crowdsourcing"
    io.fusionapp.crowdsourcing/id: "29"
    io.fusionapp.crowdsourcing/phone: "13123234212"
    io.fusionapp.crowdsourcing/province: "江苏"
    "x": "0.8264"
    "y": "0.4272"
  operation:
  - name: get-coffee
    httpAction:
      action: "GET"
      url: "http://116.62.172.30/msg?num=13860560456&msg=请去拿咖啡"
      qeuery:
        arg: ""
      headers:
        Accept: "*/*"
