apiVersion: v1
kind: Service
metadata:
  name: subject3-app-engine
spec:
  type: NodePort
  selector:
    app: subject-3
    component: app-engine
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30350
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subject3-app-engine
  labels:
    app: subject-3
    component: app-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subject-3
      component: app-engine
  template:
    metadata:
      labels:
        app: subject-3
        component: app-engine
    spec:
      volumes:
      - name: https-files
        secret:
          secretName: appengine-22018yfb1004800-cn-tls-cert
          items:
          - key: tls.crt
            path: tls.crt   
          - key: tls.key
            path: tls.key   
      containers:
      - name: compute
        image: registry.cn-shanghai.aliyuncs.com/fusion-app/subject3-app-engine:201911261706
        imagePullPolicy: IfNotPresent
        command:
        - "gunicorn"
        - "-w"
        - "4"
        - "-b"
        - "0.0.0.0:5000"
        - "--certfile"
        - "/tmp/tls.crt"
        - "--keyfile"
        - "/tmp/tls.key"
        - "main:app"
        volumeMounts:
        - name: https-files
          mountPath: /tmp/tls.crt
          subPath: tls.crt
        - name: https-files
          mountPath: /tmp/tls.key
          subPath: tls.key  
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
        ports:
        - name: http
          containerPort: 5000
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
