apiVersion: v1
kind: Service
metadata:
  name: pricesetting-svc
spec:
  type: NodePort
  selector:
    app: subject-4
    component: pricesetting
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30480
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricesetting
  labels:
    app: subject-4
    component: pricesetting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subject-4
    component: pricesetting
  template:
    metadata:
      labels:
        app: subject-4
        component: pricesetting
    spec:
      containers:
      - name: compute
        image: registry.cn-shanghai.aliyuncs.com/fusion-app/subject4-pricesetting:201911141355
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30