apiVersion: fusionapp.io/v1alpha1
kind: FusionApp
metadata:
  name: fakeapp-1
spec:
  aliasName: "家人定位器"
  icon: "https://fusion-app-1253221273.cos.ap-shanghai.myqcloud.com/apps-2.png"
  description: 
    version: "0.5.1"
    uploadTime: "2019-10-12 16:45"
  resourceClaim:
  - name: deliver
    accessMode: Exclusive
    selector:
    - key: "io.fusionapp/kind"
      op: "Eq"
      value: "crowdsourcing"