apiVersion: fusionapp.io/v1alpha1
kind: FusionApp
metadata:
  name: fakeapp-5
spec:
  aliasName: "家装助手"
  icon: "https://fusion-app-1253221273.cos.ap-shanghai.myqcloud.com/apps-6.png"
  description: 
    version: "0.2.3"
    uploadTime: "2019-11-01 14:25"
  resourceClaim:
  - name: deliver
    accessMode: Exclusive
    selector:
    - key: "io.fusionapp/kind"
      op: "Eq"
      value: "crowdsourcing"